CREATE DATABASE IF NOT EXISTS CAFEPORTAL CHARACTER SET utf8 COLLATE utf8_general_ci;
CREATE DATABASE IF NOT EXISTS CAFECENTRAL CHARACTER SET utf8 COLLATE utf8_general_ci;
CREATE DATABASE IF NOT EXISTS CAFEWORKER CHARACTER SET utf8 COLLATE utf8_general_ci;

GRANT ALL PRIVILEGES ON CAFEPORTAL.* TO 'cafe2'@'%';
GRANT ALL PRIVILEGES ON CAFECENTRAL.* TO 'cafe2'@'%';
GRANT ALL PRIVILEGES ON CAFEWORKER.* TO 'cafe2'@'%';
FLUSH PRIVILEGES;
